name: Check and Preview DNS changes

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0

      - name: DNSControl check
        uses: koenrh/dnscontrol-action@v3.31.4
        with:
          args: check

  preview:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3.6.0

      - name: DNSControl preview
        id: dnscontrol_preview
        uses: koenrh/dnscontrol-action@v3.31.4
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: preview

      - name: Comment Diff to PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.output }}
            ```
          check_for_duplicate_msg: true